### ISSUE TITLE
Not an issue - more like a question

### ISSUE THREAD

**Issue by Helicobacter1234** [heltena/Inactivity#1]
Hi,

Could You tell me please how exactly I Can use it and what exactly should be in the plist file .
What I want to achieve is to logoff user after some time of idle ...

Thank in advance.

**Comment by heltena** [comment]
Hi! If you are using SwiftUI and iOS 13 or above, you don't need to modify your plist file. Just use `InactivityWatcherView`, like this example:

    import Inactivity
    import SwiftUI
    
    struct InactiveView: View {
        var becomeActive: () -> Void
        
        var body: some View {
            NavigationView {
                VStack(spacing: 20) {
                    Spacer()
                    Image(systemName: "globe.asia.australia")
                        .foregroundColor(Color.accentColor)
                        .font(.largeTitle)
                    Text("Push the button to start...")
                    Spacer()
                }
                .navigationTitle("Your are inactive")
                .toolbar {
                    ToolbarItem(placement: .confirmationAction) {
                        Button {
                            becomeActive()
                        } label: {
                            Text("Start")
                        }
                    }
                }
            }
        }
    }
    
    struct ActiveView: View {
        var becomeInactive: () -> Void
        @State var firstOperand: String = ""
        @State var secondOperand: String = ""
        @State var resultOperand: String?
        
        func addValues() {
            guard
                let firstOperand = Int(firstOperand),
                let secondOperand = Int(secondOperand)
            else {
                resultOperand = nil
                return
            }
            resultOperand = "\(firstOperand + secondOperand)"
        }
        
        var body: some View {
            NavigationView {
                Form {
                    Section {
                        TextField("Operand", text: $firstOperand)
                        TextField("Operand", text: $secondOperand)
                        Button {
                            addValues()
                        } label: {
                            Label("Add", systemImage: "plus")
                        }
                    }
                    Section {
                        if let resultOperand = resultOperand {
                            Text(resultOperand)
                        } else {
                            Text("Not valid")
                                .foregroundColor(.secondary)
                        }
                    }
                }
                .navigationTitle("You are active!")
                .toolbar {
                    ToolbarItem(placement: .confirmationAction) {
                        Button {
                            becomeInactive()
                        } label: {
                            Text("Close")
                        }
                    }
                }
            }
        }
    }
    
    struct ContentView: View {
        var body: some View {
            InactivityWatcherView { proxy in
                InactiveView() {
                    proxy.becomeActive(timeout: 5)
                }
                ActiveView() {
                    proxy.becomeInactive()
                }
            }
        }
    }
    
    struct ContentView_Previews: PreviewProvider {
        static var previews: some View {
            ContentView()
        }
    }
  
To use it, just create an empty Xcode swiftui App project, copy&paste the code below to your ContentView.swift file, add this package to your depencencies and that's it.

**Comment by Helicobacter1234** [comment]
Hi, first of all thank You for your answer.

Im new to swift development and I'm not sure if I understand what you said.

Tell me if I'm right... I have multiple views in my app. And the first one is ContentView. That's how it looks like : 
Sorry for such a big post :(

'import SwiftUI

struct ContentView: View {
    
    @StateObject var playerModel = PlayerViewModel()
  
    var body: some View {
     
        ZStack{
           
                if (playerModel.videoDone) {
                    Home()
                }
                else
                {
                 PlayerContentView()
                }
             }
           }
         }

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}`

The second is Home View :

`struct Home: View {
    
    @StateObject var loginVM = LoginViewModel()
    @StateObject var authentication = Authentication()
    
    
    var body: some View {
        
        if authentication.isValidated {
            NavigationView{
                
                TabViewControllerView()
                    .navigationBarHidden(true)
                    .navigationBarBackButtonHidden(true)
            }
            .environmentObject(authentication)
        } else {
            NavigationView{
                
                Login()
                    .navigationBarHidden(true)
                    .navigationBarBackButtonHidden(true)
                
            }
            .environmentObject(authentication)
        }
    }
}`

The third is Login View. That's the place where You have to enter Your credentials.

`import SwiftUI
import Foundation
import Inactivity

struct Login: View {
    
    @State var isShowing: Bool = false
    @State var isDragging: Bool = false
    @State var curHeight: CGFloat = 400
    
    
    
    @Namespace var animation
    @State var show = false
    @State private var scaledUp = true
    
    @StateObject var loginVM = LoginViewModel()
    @EnvironmentObject var authentication: Authentication
   
    @Environment(\.colorScheme) var colorScheme
    
    var body: some View {
        
        VStack {
            
            Image(uiImage: UIImage(named: colorScheme == .dark ? "logo_white" : "logo")!).resizable().aspectRatio(contentMode: .fit)
                .frame(width: 220.0, height: 220.0)
            
            Text("IWorkFlow")
            Text("1.0")
            
            Spacer(minLength: 0)
            
            HStack {
                
                VStack(alignment: .leading, spacing: 10) {
                    
                    Text("Login")
                        .font(.system(size: 40, weight: .heavy))
                        .foregroundColor(.primary)
                    Text("Zaloguj się, aby kontynuować")
                        .fontWeight(.semibold)
                        .foregroundColor(.gray)
                }
                Spacer(minLength: 0)
            }
            .padding()
            .padding(.leading)
            
            CustomTextField(image: "person", title: "Użytkownik", value: $loginVM.credentials.userName, animation: animation)
            
            CustomTextField(image: "lock", title: "Hasło", value: $loginVM.credentials.password, animation: animation)
                .padding(.top,5)
            
            HStack {
                
                Spacer(minLength: 0)
                
                VStack(alignment: .trailing, spacing: 20) {
                    
                    Button(action: {}) {
                        Text("Zapomniałem hasło")
                            .fontWeight(.heavy)
                            .foregroundColor(Color("yellow"))
                    }
                    
                    HStack {
                        if loginVM.showProgressView {
                            ProgressView()
                        }
                        
                      
                        
                        Button() {
                            loginVM.login { success in
                                authentication.updateValidation(success: success)
                            }
                        }
                    label: {
                        Image(systemName: "arrow.right")
                            .font(.title2)
                        Text("LOGIN")
                            .fontWeight(.heavy)
                    }.disabled(loginVM.loginDisabled)
                    .modifier(CustomButtonModifier())
                        
                        if authentication.biometricType() != .none {
                            
                            Button {
                                authentication.requestBiometricUnlock { (result:Result<Credentials, Authentication.AuthenticationError>) in
                                    switch result {
                                    case .success(let credentials):
                                        loginVM.credentials = credentials
                                        loginVM.login { success in
                                            authentication.updateValidation(success: success)
                                        }
                                    case .failure(let error):
                                        loginVM.error = error
                                    }
                                }
                            } label: {
                                Image(systemName: authentication.biometricType() == .face ? "faceid" : "touchid")
                                    .resizable()
                                    .frame(width: 50, height: 50)
                            }
                        }
                    }
                    
                    if loginVM.isLoading {
                        
                        ProgressView("Trwa logowanie…")
                            .scaleEffect(3)
                            .font(.system(size:5))
                            .padding(5)
                    }
                }.fullScreenCover(isPresented: self.$loginVM.isAuthenticated, content: {
                    TabViewControllerView()
                        .edgesIgnoringSafeArea(.all)
                        .animation(.linear(duration: 2), value: scaledUp)
                        .transition(.move(edge: .bottom))
                })
            }
            
            .padding()
            .padding(.top,10)
            .padding(.trailing)
            
            Spacer(minLength: 0)
            
            HStack(spacing: 8) {
                
                Text("Nie posiadasz konta?")
                    .fontWeight(.heavy)
                    .foregroundColor(.gray)
                
                NavigationLink(destination: Register(show: $show), isActive: $show) {
                    
                    Text("Zarejestruj się")
                        .fontWeight(.heavy)
                        .foregroundColor(Color("yellow"))
                }
                
            }.padding()
        }.disabled(loginVM.showProgressView)
            .alert(item: $loginVM.error) { error in
                
                if error == .credentialsNotSaved {
                    return Alert(title: Text("Dane logowania nie zostały zapisane"),
                                 message: Text(error.localizedDescription),
                                 primaryButton: .default(Text("OK"), action: {
                        loginVM.storeCredentialsNext = true
                    }),
                                 secondaryButton: .cancel())
                } else {
                    return Alert(title: Text("Wystąpuł błąd"), message: Text(error.localizedDescription))
                }
            }
    }
}


struct Login_Preview: PreviewProvider {
    static var previews: some View {
        Login()
    }
}`


The last one where user is going to after a successful login is  TabViewControllerView() :

`import SwiftUI
import Foundation
import Inactivity

struct TabViewControllerView: View {
    
    @EnvironmentObject var authentication: Authentication
    
    var body: some View {
     
        if authentication.isValidated {
            TabBarView().onInactivityStateChanged { state in print("Going to \(state)")}
        }else {
            Home()
        }
    }
}`

And it is TabBarView at the end :

`import Foundation
import SwiftUI
import Inactivity

struct TabBarView : View {
    
    @EnvironmentObject var authentication: Authentication
    @StateObject var loginVM = LoginViewModel()
    @State var selectedTab = "Akceptacja"
    @Environment(\.scenePhase) var scenePhase
    
    var edges = UIApplication.shared.keyWindow?.safeAreaInsets.swiftUiInsets ?? EdgeInsets()
    //UIApplication.shared.windows.first?.safeAreaInsets

    @Namespace var animation
    @StateObject var modelData = ModelView()
    
    var body: some View{
        
        VStack(spacing: 0){
            
            GeometryReader{_ in
                
                ZStack{
                    
                    CorespondenceListView().opacity(selectedTab == "Akceptacja" ? 1 : 0)
                        .environmentObject(authentication)
                        .onInactivityStateChanged { state in print("Going to \(state)")}
                    
                    Text("Historia").opacity(selectedTab == "Historia" ? 1 : 0)
                        .environmentObject(authentication)
                        .onInactivityStateChanged { state in print("Going to \(state)")}
                    
                    Text("Inne")
                        .opacity(selectedTab == "Inne" ? 1 : 0)
                        .environmentObject(authentication)
                        .onInactivityStateChanged { state in print("Going to \(state)")}
                    
                    SettingsView()
                        .environmentObject(authentication)
                        .opacity(selectedTab == "Ustawienia" ? 1 : 0)
                        .onInactivityStateChanged { state in print("Going to \(state)")}
                        
                    
                }
            }
            .onChange(of: selectedTab) { (_) in
                
                switch(selectedTab){
                
                case "Historia": if !modelData.isHistoryLoad{modelData.loadHistory()}
                case "Inne": if !modelData.isOtherLoad{modelData.loadOthers()}
                case "Ustawienia": if !modelData.isSettingsLoad{modelData.loadSettings()}
                default: ()
                }
            }
            .onInactivityStateChanged { state in print("Going to \(state)") }
    
            // TabView...
            
            HStack(spacing: 0){
                
                ForEach(tabs,id: \.self){tab in
                    
                    TabButton(title: tab, selectedTab: $selectedTab,animation: animation)
                    
                    if tab != tabs.last{
                        Spacer(minLength: 0)
                    }
                }
            }
            .padding(.horizontal,30)
            // for iphone like 8 and SE
            .padding(.bottom, edges.bottom == 0 ? 15 : edges.bottom)
            .background(Color(UIColor.systemBackground))
        }
        .ignoresSafeArea(.all, edges: .bottom)
        .background(Color.black.opacity(0.06).ignoresSafeArea(.all, edges: .all))
        .navigationViewStyle(StackNavigationViewStyle())
    }
}

// Tab Button...

struct TabButton : View {
    
    @Environment(\.colorScheme) var colorScheme
    var title : String
    @Binding var selectedTab : String
    var animation : Namespace.ID
    
    var body: some View{
        
        Button(action: {
            withAnimation{selectedTab = title}
        }) {
            
            VStack(spacing: 6){
                
                // Top Indicator....
                
                // Custom Shape...
                
                // Slide in and out animation...
                
                ZStack{
                    
                    CustomShape()
                        .fill(Color.clear)
                        .frame(width: 45, height: 6)
                    
                    if selectedTab == title{
                        
                        CustomShape()
                            .fill(Color("tint"))
                            .frame(width: 45, height: 6)
                            .matchedGeometryEffect(id: "Tab_Change", in: animation)
                    }
                }
                .padding(.bottom,10)
                
                Image(title)
                    .renderingMode(.template)
                    .resizable()
                    .foregroundColor(selectedTab == title ? Color("tint") : ((colorScheme == .dark) ? Color.white.opacity(0.2) : Color.black.opacity(0.2)))
                    .frame(width: 24, height: 24)
                
                Text(title)
                    .font(.caption)
                    .fontWeight(.bold)
                    .foregroundColor((colorScheme == .dark) ? Color.white.opacity(selectedTab == title ? 0.6 : 0.2) : Color.black.opacity(selectedTab == title ? 0.6 : 0.2))
            }
        }
    }
}

// Custom Shape..

struct CustomShape: Shape {
    
    func path(in rect: CGRect) -> Path {
        
        let path = UIBezierPath(roundedRect: rect, byRoundingCorners: [.bottomLeft,.bottomRight], cornerRadii: CGSize(width: 10, height: 10))
        
        return Path(path.cgPath)
    }
}

// Both Title Image Name Are Same....
var tabs = ["Akceptacja","Historia","Inne","Ustawienia"]

// if You Having simply views and not that much network task means its fine
// else use this method to load data when the tab opens....

class ModelView : ObservableObject{
    
    @Published var isOtherLoad = false
    @Published var isHistoryLoad = false
    @Published var isSettingsLoad = false
    
    init() {
        
        // load initial data
        print("Akceptacja Data Loaded")
    }
    
    func loadOthers(){
        
        print("Inne Loaded")
        isOtherLoad = true
    }
    
    func loadHistory(){
        
        print("Historia Loaded")
        isHistoryLoad = true
    }
    
    func loadSettings(){
        
        print("Ustawienia Loaded")
        isSettingsLoad = true
    }
}

extension UIApplication {
    var keyWindow: UIWindow? {
        connectedScenes
            .compactMap {
                $0 as? UIWindowScene
            }
            .flatMap {
                $0.windows
            }
            .first {
                $0.isKeyWindow
            }
    }
}

private struct SafeAreaInsetsKey: EnvironmentKey {
    static var defaultValue: EdgeInsets {
        UIApplication.shared.keyWindow?.safeAreaInsets.swiftUiInsets ?? EdgeInsets()
    }
}

extension EnvironmentValues {
    var safeAreaInsets: EdgeInsets {
        self[SafeAreaInsetsKey.self]
    }
}

private extension UIEdgeInsets {
    var swiftUiInsets: EdgeInsets {
        EdgeInsets(top: top, leading: left, bottom: bottom, trailing: right)
    }
}`

My question is Do I have to wrap up each view individually with the "`struct InactiveView: View {
    var becomeActive: () -> Void`" or each view is going to have a var becomeActive: () -> Void and then when I tapped on a button or navigate to another view I will know that my app is Active ? But I don't understand how will I know that my app is InActive - I mean idle - cause what I want to achieve is to logOff user after some time of being idle :(

Again very sorry that this post is so long but I want to show You how my app looks like. I hope you are not angry about that.
Thanks in advance

**Comment by Helicobacter1234** [comment]
Hi again,

Thank You for Your answer.
Now it is working :)

I have only one question how can I (is it even possible) to return Alert to User when app is going to log off. 

I was trying to do something like this :

            InactivityWatcherView { proxy in
              
                Login() {
                           proxy.becomeActive(timeout: 30)
                       }
                TabBarView(){
                              proxy.becomeInactive()
                            } .onInactivityStateChanged { state in if "\(state)" == "inactive" {
                                  Alert(title: Text("Automatic log off"),
                                        message: Text("App log off because of inactivity"),
                                        dismissButton: .default(Text("OK"))
                       )}}
                   }

**Comment by Helicobacter1234** [comment]
Thank You - Everything is working Perfectly :) Great job :)

**Comment by heltena** [comment]
Perfect, happy you did it! Closing the issue ;-)

**Comment by aehlke** [comment]
Would be great to have a small example app with this, or just putting this right into the readme

**Comment by heltena** [comment]
> Would be great to have a small example app with this, or just putting this right into the readme

Find it here: https://github.com/heltena/InactivityExample

Just added, it was not there when you checked it ;-)
